import { PrismaClient, CourseLevel, CourseStatus, LessonStepType, AssignmentStatus } from '@prisma/client';

const prisma = new PrismaClient();

// Helper to create step ID
function makeStepId(lessonId: string, type: string) {
  return `${lessonId.substring(0, 18)}-${type}`;
}

// Detailed educational content for all 44 lessons
const lessonContents: Record<string, string> = {
  // Module 1
  "What is AI?": `# Foundations of AI

Artificial Intelligence (AI) is the science of creating computer systems that can perform tasks that would normally require human intelligence. This includes learning from experience, recognizing visual patterns, translating languages, and making decisions.

### Traditional Software vs. AI:
* **Traditional Software**: Follows a strict set of instructions written by a programmer. If condition A is met, do B. It cannot adapt to inputs it was not explicitly programmed for.
* **AI Systems**: Learn rules from examples. They analyze data, identify underlying relationships, and adapt their outputs dynamically.

---

### Key AI Terminology:
1. **Algorithm**: A step-by-step set of instructions for a computer to follow.
2. **Model**: The mathematical output generated by training an algorithm on data.
3. **Training**: The process of feeding data to an algorithm so it can learn patterns.`,

  "History of AI": `# The Story of AI

The quest to build intelligent machines spans several decades, marked by massive breakthroughs and periods of stagnation known as **AI Winters**:

* **1950: Alan Turing's Vision**: Alan Turing publishes "Computing Machinery and Intelligence," introducing the famous *Turing Test* to check if a machine can pass as human.
* **1956: The Dartmouth Workshop**: John McCarthy officially coins the term "Artificial Intelligence" at a summer workshop, marking the birth of the field.
* **1974-1980: The First AI Winter**: High expectations lead to disappointment when computers lack the memory and processing power to solve real-world problems. Funding is cut.
* **1997: Deep Blue Defeats Kasparov**: IBM's chess-playing supercomputer beats world chess champion Garry Kasparov, reviving interest and research.
* **2012: The Deep Learning Revolution**: Breakthroughs in GPU processing power and neural networks enable rapid progress in image classification (ImageNet).
* **2020+: Generative AI**: Large Language Models (like GPT) capture global attention with human-like text and media generation.`,

  "AI Around Us": `# AI in Our Everyday Lives

Whether you realize it or not, you interact with Artificial Intelligence systems multiple times a day:

* **Smartphone Face Unlock**: Convolutional Neural Networks analyze your facial contours to unlock your phone securely.
* **Predictive Text**: Autocomplete and autocorrect algorithms predict the next word you want to type based on your past conversations.
* **Real-time Traffic Routing**: Navigation apps analyze historical trip logs, live construction feeds, and user speeds to calculate the optimal path.
* **Recommendation Feeds**: Streaming systems analyze your watch history and predict what movie or music track will keep you engaged.`,

  "AI vs Human Intelligence": `# AI vs Human Intelligence

How close is AI to matching the capabilities of the human mind? Let's compare their structural differences:

| Metric | Artificial Intelligence (AI) | Human Intelligence |
| :--- | :--- | :--- |
| **Processing Speed** | Gigahertz (billions of calculations per second). | Miliseconds (neurons fire slower but in parallel). |
| **Adaptability** | Hard to adapt to completely new tasks without retraining. | Highly flexible; can apply learning to unrelated domains. |
| **Energy Consumption**| Requires Megawatts of server power. | Highly efficient, requiring roughly 20 Watts (a lightbulb). |
| **Emotional Intelligence**| Simulated response; lacks consciousness. | Genuine empathy, self-awareness, and emotions. |`,

  "Types of AI (Narrow AI vs General AI)": `# Scoping AI Capabilities

AI is broadly classified into three developmental stages:

### 1. Artificial Narrow AI (ANI)
Also known as *Weak AI*, ANI is designed to perform a single, specific task exceptionally well (e.g., play chess, translate text, recommend movies). All current AI systems (including ChatGPT, Siri, and self-driving cars) are Narrow AI. They cannot apply their intelligence to tasks outside their programmed domain.

### 2. Artificial General AI (AGI)
Also known as *Strong AI*, AGI represents hypothetical software that has human-level intelligence across all domains. An AGI could learn new skills, reason, plan, and perform any intellectual task a human can. We have not achieved AGI yet.

### 3. Artificial Super AI (ASI)
ASI represents a hypothetical future where AI capabilities surpass human intelligence in every aspect, including creativity, scientific reasoning, and social skills.`,

  "Fun AI Quiz": `# Fun AI Quiz

Let's test what you've learned in this module! Double check your understanding of Narrow AI, General AI, and traditional programming before launching the quiz in the next step.

* **Tip**: Narrow AI can only do specific tasks, while General AI is human-level and multi-purpose.`,

  // Module 2
  "AI in Mobile Phones": `# AI in Mobile Phones

Modern smartphones are packed with hardware specifically optimized for artificial intelligence, often called **Neural Processing Units (NPUs)**:

### 1. Computational Photography
When you click a photo, AI algorithms instantly perform "semantic segmentation" (separating the sky, skin tones, and foreground objects) to adjust colors, reduce noise, and create depth effects.

### 2. Battery Optimization
AI monitors your daily usage patterns to predict when you will open specific apps. It pre-loads those apps to make them feel faster and puts background tasks to sleep to extend battery life.`,

  "AI in YouTube & Netflix Recommendations": `# Inside Recommendation Engines

How do streaming systems know what you want to watch next? They use two main types of filtering:

### 1. Collaborative Filtering
This method recommends items by finding similar users. If User A and User B both enjoyed Movies X and Y, and User A recently enjoyed Movie Z, the system will recommend Movie Z to User B.

### 2. Content-Based Filtering
This method recommends items based on the properties of the item itself. If you watch a lot of science-fiction movies starring a specific actor, the system will suggest other sci-fi movies matching those criteria.`,

  "AI in Google Maps": `# AI in Google Maps

Google Maps uses a combination of historical data and live telemetry to route you efficiently:

* **Predictive Arrival Times (ETA)**: Machine learning models analyze historical traffic speeds for specific times of the day, combined with live sensor data from other active phones on the road.
* **DeepMind Graph Neural Networks**: These models analyze spatial structures (how segments of roads connect) to predict complex traffic patterns minutes before they occur.`,

  "AI in Online Shopping": `# AI in E-Commerce

Online retailers use predictive AI to optimize your shopping experience and manage inventory:

* **Dynamic Pricing**: E-commerce algorithms adjust prices in real-time based on demand, stock levels, competitor pricing, and shopping seasons.
* **Fraud Detection**: AI monitors transactions for unusual patterns (such as purchases made in two different countries within a short timeframe) and flags them for verification.
* **Search Personalization**: Search results are ranked based on your individual purchase history and browsing clicks.`,

  "AI in Games": `# AI in Video Games

AI in gaming has evolved from simple rule-based pathfinding to adaptive systems:

* **Non-Player Characters (NPCs)**: Use finite state machines or behavior trees to react to player movements, seek cover, and coordinate attacks.
* **Procedural Content Generation (PCG)**: Algorithms generate massive game worlds, terrain, and quests dynamically (e.g. in Minecraft or No Man's Sky) to save storage space and increase replayability.
* **Reinforcement Learning**: Modern AI models (like AlphaStar) train by playing against themselves millions of times to beat top professional human gamers in strategy matches.`,

  "AI in Healthcare and Education": `# AI in Healthcare and Education

AI is making high-quality healthcare and education more accessible and personalized:

### Healthcare Applications:
* **Medical Imaging**: Convolutional Neural Networks can analyze MRI and X-ray scans to detect early-stage tumors with higher accuracy than general radiologists.
* **Drug Discovery**: AI simulations predict how chemical structures will bind to target proteins, shortening the drug discovery timeline from years to weeks.

### Educational Applications:
* **Personalized Learning**: Adaptive tutors analyze your quiz scores and supply custom reviews targeting your weak areas.
* **Automated Grading**: AI highlights grammar and structural errors in student essays, saving teachers hours of review.`,

  // Module 3
  "What is Machine Learning?": `# What is Machine Learning?

Machine Learning (ML) is a subset of Artificial Intelligence that allows computers to learn from data without being explicitly programmed.

### The Paradigm Shift:
* **Traditional Coding**:
  \`\`\`
  Data + Rules ──> [ Computer Program ] ──> Answers/Outputs
  \`\`\`
* **Machine Learning**:
  \`\`\`
  Data + Answers ──> [ Training Phase ] ──> Rules (Model)
  \`\`\`

Once the model learns the "Rules" (called features and weights), we can feed it new data to predict outputs automatically.`,

  "How Machines Learn": `# How Machines Learn

Machines learn patterns by adjusting internal numbers (called **weights** and **biases**) using mathematical feedback loops:

### Three Core Types of Machine Learning:
1. **Supervised Learning**: The algorithm is trained on labeled data (input and target output). For example, training a model with 1,000 photos of cats labeled "cat" and 1,000 photos of dogs labeled "dog."
2. **Unsupervised Learning**: The algorithm is fed unlabeled data and must discover hidden structures or groups on its own (e.g., clustering retail customers into buying groups).
3. **Reinforcement Learning**: The algorithm learns by trial and error, receiving positive rewards for good actions and negative feedback for bad actions (e.g., teaching an AI to play chess).`,

  "Data: The Fuel of AI": `# Data: The Fuel of AI

In machine learning, the quality and quantity of your data determine the performance of your model. There is a common phrase: *Garbage In, Garbage Out*.

### Key Data Processing Steps:
* **Data Collection**: Gathering raw text, images, or numerical records.
* **Data Cleaning**: Removing duplicates, fixing missing values, and correcting errors.
* **Labeling**: Adding target tags (e.g., marking email records as "spam" or "inbox").
* **Feature Extraction**: Selecting the most important attributes that help the model make accurate predictions (e.g., using square footage and location to predict house prices).`,

  "Training vs Testing": `# Training vs. Testing

To verify if a machine learning model actually works, we must split our dataset into two distinct parts:

### 1. Training Set (typically 80%)
This data is used to teach the model. The algorithm processes these examples repeatedly, adjusting its weights to minimize errors.

### 2. Testing Set (typically 20%)
This data is kept hidden from the model during training. Once the model is trained, we make predictions on the test set to verify its real-world accuracy.

> [!WARNING]
> If you test your model on the same data you used to train it, it will score 100% simply by memorizing the answers. This is a common error called **Overfitting**.`,

  "Examples of Machine Learning": `# Machine Learning in Action

Here are typical real-world machine learning tasks categorized by output type:

* **Regression**: Predicting a continuous numerical value (e.g. predicting a house price based on size, or stock prices).
* **Classification**: Predicting a discrete label or category (e.g. classifying emails as spam or not spam, or identifying hand-written digits).
* **Clustering**: Grouping similar items together without predefined categories (e.g. grouping news articles by topic, or segmenting customers based on purchase behavior).`,

  "Lab: Basic Machine Learning Analogy": `# Lab: Fruits Classifier

Let's write a simple programmatic fruit classifier simulating how decision trees make boundaries. You will build a classifier returning 'grape', 'apple', or 'unknown' based on weight and color parameters.`,

  // Module 4
  "What is Generative AI?": `# What is Generative AI?

Generative AI refers to algorithms (such as Large Language Models and Diffusion Models) that can create new content, including text, images, audio, video, and synthetic data.

### How it works:
Unlike analytical AI (which categorizes or predicts existing data), Generative AI is trained on massive datasets to understand the underlying statistical probability of text words or image pixels. It uses this probability to generate original sequences of content that match the style and structure of its training examples.`,

  "ChatGPT and AI Chatbots": `# Chatbots and Large Language Models

AI chatbots like ChatGPT, Claude, and Gemini are powered by **Large Language Models (LLMs)**:

### 1. The Transformer Architecture
Developed by Google researchers in 2017, this architecture uses a mechanism called "attention" to understand the relationship between words in a sentence, even if they are far apart.

### 2. Next-Token Prediction
At their core, LLMs operate by predicting the next word (or token) in a sentence based on the statistical probabilities learned during training. It evaluates the prompt you wrote and outputs the most likely next word, repeating this loop to generate complete paragraphs.`,

  "AI Image Generation": `# AI Image Generation

AI systems can generate highly detailed images from text descriptions using two main technologies:

### 1. Generative Adversarial Networks (GANs)
Uses two neural networks competing against each other: a *Generator* (which creates fake images) and a *Discriminator* (which tries to detect if the image is real or fake). They train together until the generator's images are indistinguishable from real photos.

### 2. Diffusion Models
Works by adding noise (random pixels) to an image during training, and then learning how to reverse that process (denoising) to construct clean images starting from pure random pixel noise based on text prompts.`,

  "AI Music and Video Generation": `# AI Music and Video Generation

The generative revolution has expanded beyond text and images into dynamic media:

* **AI Music**: Algorithms analyze music theory, melodies, and beats to generate full instrumental tracks or synthesize lyrics in specific genres (e.g. Suno or Udio).
* **AI Video**: Models analyze spatial movements and lighting across frames to generate fluid, high-fidelity video clips from text instructions (e.g., OpenAI's Sora).`,

  "Benefits and Limitations": `# Benefits and Limitations of Generative AI

While Generative AI is incredibly powerful, it has major technical limits:

### Benefits:
* **Productivity**: Instantly generates draft articles, code templates, or design mockups.
* **Brainstorming**: Helps overcome writer's block by suggesting ideas.

### Limitations:
* **Hallucinations**: AI models write false information with absolute confidence because they predict statistical word sequences rather than checking actual facts.
* **Lack of Context**: They do not have real-world experience, common sense, or understanding of meaning.`,

  // Module 5
  "What is a Prompt?": `# What is a Prompt?

A **Prompt** is the text instruction or query you input into an AI model to guide its output:

### The Importance of Prompting:
LLMs are highly sensitive to their inputs. Changing a single word or restructuring your sentence can completely alter the response. Learning to write good prompts is called **Prompt Engineering**.

Think of the AI model as an eager assistant: it has access to vast information, but it needs precise instructions to complete tasks exactly the way you want.`,

  "Good vs Bad Prompts": `# Good vs. Bad Prompts

Writing generic prompts leads to generic, vague answers. Let's compare:

* **Bad Prompt**: *"Write a story."*
  * **Result**: The AI will write a generic story with random characters, genre, and length.
* **Good Prompt**: *"Write a 200-word sci-fi story about an astronaut who gets locked outside their space station. The tone should be suspenseful."*
  * **Result**: The AI matches the length, genre, characters, and emotional tone precisely.

---

### The Prompt Formula:
> **Prompt Formula**: Prompt = Instruction + Context + Input Data + Output Formatting`,

  "Asking Better Questions": `# Asking Better Questions

To get highly structured answers from AI chatbots, include these components:

* **Role**: Tell the AI who it should act as (e.g., *"Act as a senior python developer"*).
* **Constraints**: Set boundaries (e.g., *"Do not write external library dependencies"*).
* **Target Audience**: Specify who the output is for (e.g., *"Explain this to a 10-year-old child"*).
* **Examples (Few-Shot Prompting)**: Supply examples of inputs and desired outputs to teach the model the pattern.`,

  "Role-Based Prompting": `# Role-Based Prompting

Role-Based prompting instructs the AI model to adopt a specific persona, which shifts its vocabulary, tone, and level of expertise:

### Example Personas:
* *"Act as a strict editor. Proofread my text for grammar, punctuation, and flow, returning only the corrected version."*
* *"Act as a career counselor. Interview me about my skills and interests one question at a time to suggest three jobs."*
* *"Act as a Socratic tutor. Do not give me the answers directly; instead, ask me questions that lead me to find the answer myself."*`,

  "Prompt Templates": `# Prompt Templates

Templates are reusable prompt structures that accept variables, making it easy to automate repetitive tasks:

### Example Template:
\`\`\`
Task: Translate the following text into [Language].
Tone: [Professional/Casual]
Text: "[User Input Text]"
\`\`\`

By saving prompt templates, you can consistently get high-quality, formatted outputs without rewriting the prompt from scratch every time.`,

  "Lab: Refining Bad Prompts": `# Lab: Improving Prompts

Let's write a prompt template function. You will build a function that takes a raw query and improves it by adding a target audience and format constraint.`,

  // Module 6
  "Responsible AI": `# Responsible AI

Responsible AI is the practice of designing, developing, and deploying AI systems that are safe, ethical, and fair.

### 5 Core Principles of Responsible AI:
1. **Fairness**: AI should treat all groups of people equally.
2. **Transparency**: Creators should explain how models make decisions.
3. **Privacy**: User data must be protected and not leaked during training.
4. **Safety**: AI systems must operate reliably and not cause harm.
5. **Accountability**: Developers must take responsibility for the outputs of their models.`,

  "Bias in AI": `# Bias in AI

AI models learn from historical datasets collected by humans. If the training data contains biases or inequalities, the AI model will learn and amplify those biases.

### Real-world Examples:
* **Recruiting Tools**: An AI resume screening tool trained on historical hiring data of mostly men in engineering roles began penalizing resumes containing the word "women's."
* **Facial Recognition**: Early facial recognition algorithms had higher error rates for individuals with darker skin tones because the training images were predominantly of light-skinned individuals.`,

  "Fake Images & Deepfakes": `# Deepfakes and Media Ethics

**Deepfakes** are synthetic media where a person's face or voice is realistically replaced with someone else's using deep learning models:

### The Risks:
* **Spreading Misinformation**: Generating fake videos of politicians making statements they never made.
* **Identity Theft**: Impersonating family members using voice clones to execute financial scams.
* **Consent Issues**: Placing individuals' faces onto explicit media without their consent.

---

### How to Spot Fake Media:
* Look for unnatural blinking patterns or weird lighting outlines.
* Listen for robotic pacing or static audio transitions.`,

  "Privacy": `# AI and Data Privacy

When you type questions, code, or personal documents into public AI chatbots, that data is sent to the developer's servers and may be used to train future versions of the model.

### Key Privacy Guidelines:
* **No Personal Data**: Never input passwords, phone numbers, or credit card details.
* **No Confidential Code**: Tech companies restrict employees from pasting proprietary code into public models to prevent trade-secret leaks.
* **Check Settings**: Most public AI chat tools allow you to opt-out of data sharing or history tracking in settings.`,

  "AI Hallucinations": `# AI Hallucinations

An AI **Hallucination** occurs when a model generates false or nonsensical statements with absolute confidence:

### Why it happens:
LLMs do not have access to an internal database of truth. They predict the most statistically probable next word. If the model has limited training details on a niche topic, its prediction loop will generate details that sound grammatically correct but are entirely fabricated.

> [!IMPORTANT]
> Never assume AI facts are correct. Always verify critical details (citations, medical advice, code functions) using primary search engines or official documentation.`,

  "Using AI Safely": `# Using AI Safely

Here is a summary of best practices for using AI ethically and safely as a student:

* **Use as an Assistant**: Use AI to brainstorm, structure outlines, or explain difficult concepts. Do not copy and paste entire essays to pass them off as your own work.
* **Verify Outputs**: Treat every AI output as a draft that needs human review.
* **Be Aware of Academic Integrity**: Always verify your school's rules on using generative tools for homework and projects.`,

  // Module 7
  "AI Story Generator": `# Lab: Story Generator Prompt

Let's write a python function that structures a prompt instructing a model to write a short story. You will format the prompt strings using variables for the hero and the genre.`,

  "AI Poster Creator": `# AI Poster Creator

Learn how to write descriptive image prompts to generate posters:

### Structuring Image Prompts:
* **Subject**: What is the main focal point? (e.g. *"A cute orange robot"*).
* **Environment/Background**: Where is it? (e.g. *"on a crowded cyberpunk city street"*).
* **Style**: What medium? (e.g. *"digital art, 3D render, cartoon"*).
* **Lighting/Color**: Bright, neon, dark, cinematic, pastel.
* **Resolution/Details**: high detail, octane render, 8k.

Example: *"A vector illustration of a rocket ship flying through a galaxy of neon stars, pastel color palette, minimalist design."*`,

  "AI Quiz Maker": `# Lab: Quiz JSON Maker

Let's build a JavaScript utility that outputs structured JSON quiz schemas. This simulates how AI chatbots output formatted code configurations that back educational games.`,

  "AI Study Assistant": `# Building an AI Study Assistant

You can build custom study assistants using prompt engineering strategies:

### Example System Instructions:
\`\`\`
"You are a friendly high school biology tutor. 
Ask me a multiple-choice question about the cell membrane. 
Wait for my answer. 
If my answer is correct, congratulate me and ask the next question. 
If incorrect, explain the concept simply and ask me to try again."
\`\`\`

By configuring chat models with these constraints, you turn generic chat systems into interactive learning tools.`,

  "AI Travel Planner": `# AI Travel Planner

Travel planning is a great multi-step prompt engineering activity:

### Structure:
1. **Destination & Duration**: *"Create a 3-day itinerary for Tokyo, Japan."*
2. **Interests**: *"Focus on historical temples and local street food."*
3. **Constraints**: *"Keep travel distance minimal between sights. Budget is 150 USD per day."*
4. **Format**: *"Present the response as a table with columns: Time, Location, Estimated Cost, and Tips."*`,

  // Module 8
  "AI Careers": `# Careers in the AI Space

The rapid growth of AI has created high-demand careers across multiple roles:

* **Machine Learning Engineer**: Designs, builds, and deploys algorithms and neural network models in production.
* **Data Scientist**: Collects, cleans, and analyzes massive datasets to find patterns that help train ML models.
* **Prompt Engineer**: Optimizes text inputs to get consistent, high-quality responses from generative models.
* **AI Ethics Officer**: Evaluates AI systems for fairness, bias, privacy violations, and safety concerns.`,

  "Robots and Automation": `# Robots and Automation

Robotics combines mechanical engineering, electronics, and AI:

* **Industrial Robots**: Perform repetitive tasks (such as welding car parts) with millimeter precision.
* **Autonomous Mobile Robots (AMRs)**: Navigate through warehouses dynamically to transport packages (e.g. Amazon warehouse bots).
* **Humanoid Robots**: Future humanoid bots learn physics and movements by watching human video inputs and training in physics simulations.`,

  "AI in Space": `# AI in Space Exploration

Space agencies use AI to navigate and analyze massive astronomical streams:

* **Rover Autonomy**: Mars rovers (like Perseverance) use computer vision to map out hazards and steer themselves autonomously without waiting for instructions from Earth (which takes 20 minutes to travel).
* **Exoplanet Discovery**: Machine learning models analyze raw light curves from telescopes to detect tiny drops in light, identifying new planets orbiting distant stars.`,

  "AI in Medicine": `# AI in Medicine

AI is transforming diagnostic accuracy and custom medicine plans:

* **Surgical Robotics**: AI assists surgeons in performing precise, minimally invasive incisions.
* **Genomic Medicine**: ML models analyze genetic data to predict which medical treatments will be most effective for an individual patient.
* **Epidemiology**: AI analyzes search trends, travel plans, and news reports to predict the spread of infectious diseases.`,

  "Future Jobs": `# Future Jobs in the AI Era

AI will automate repetitive tasks, but it will also create brand new jobs that do not exist today:

* **AI Trainer**: Feeds data and corrects AI chatbot behaviors.
* **Deepfake Detectors**: Cybersecurity experts specialized in verifying media authenticity.
* **Custom AI Integrators**: Consultants who help small companies automate tasks using public LLM APIs.
* **VR/AR Experience Creators**: Design interactive simulated worlds powered by generative assets.`,

  "Becoming an AI Creator": `# Becoming an AI Creator

You do not need a PhD to start building with AI today. Here is a roadmap to become an AI creator:

1. **Learn Python**: The most popular language for machine learning due to libraries like NumPy, Pandas, and PyTorch.
2. **Experiment with APIs**: Use simple fetch calls to connect to OpenAI, Claude, or local Ollama models.
3. **Take Free Courses**: Platforms like Kaggle, Google, and fast.ai offer great hands-on tutorials.
4. **Build Projects**: Build a simple classification model or a prompt-based chatbot and share it!`,
};

async function main() {
  console.log('🌱 Seeding Detailed Beginner AI Course...');

  // Clean up existing course if it exists to allow clean re-runs
  const existingCourse = await prisma.course.findUnique({
    where: { slug: 'intro-to-ai-for-beginners' }
  });
  if (existingCourse) {
    console.log('Cleaning up existing AI course and related steps...');
    await prisma.course.delete({
      where: { id: existingCourse.id }
    });
  }

  // 1. Fetch AI & ML Category
  let category = await prisma.category.findUnique({
    where: { slug: 'ai-ml' }
  });
  if (!category) {
    category = await prisma.category.create({
      data: { name: 'AI & ML', slug: 'ai-ml', icon: '🤖', sortOrder: 3 }
    });
  }

  // 2. Fetch Instructor
  let instructor = await prisma.user.findFirst({
    where: { role: 'instructor' }
  });
  if (!instructor) {
    instructor = await prisma.user.create({
      data: {
        clerkId: 'usr_instructor_1',
        email: 'priya@skilotech.com',
        firstName: 'Priya',
        lastName: 'Sharma',
        username: 'priya_sharma',
        avatarUrl: '👩‍🏫',
        role: 'instructor',
        bio: 'Senior Software Engineer and Educator.',
        phone: '+919876543211',
        isVerified: true,
      }
    });
  }

  // 3. Create Course
  const course = await prisma.course.create({
    data: {
      title: 'Introduction to AI for Beginners',
      slug: 'intro-to-ai-for-beginners',
      description: 'The ultimate, student-friendly introduction to Artificial Intelligence. Learn what AI is, prompt engineering, how machines learn, Generative AI tools, and AI ethics. Complete 5 hands-on projects, interactive quizzes, and Python/JS exercises. No prior coding experience required!',
      shortDescription: 'Master Artificial Intelligence basics, prompt engineering, Generative AI, and write basic ML models.',
      instructorId: instructor.id,
      categoryId: category.id,
      level: CourseLevel.beginner,
      status: CourseStatus.published,
      price: 149900, // ₹1,499.00
      currency: 'INR',
      thumbnailUrl: '/course-ai.jpg',
      durationHours: 24.0,
      studentsEnrolled: 0,
      ratingAvg: 0.0,
      ratingCount: 0,
      isFeatured: true,
    }
  });

  console.log(`Created Course: "${course.title}"`);

  // Define curriculum mapping for modules and lessons
  const modulesData = [
    {
      title: 'What is Artificial Intelligence?',
      description: 'Discover the definition of AI, its historical highlights, its presence around us, and types of AI systems.',
      lessons: [
        { title: 'What is AI?', duration: 15, free: true },
        { title: 'History of AI', duration: 15, free: true },
        { title: 'AI Around Us', duration: 20, free: true },
        { title: 'AI vs Human Intelligence', duration: 20 },
        { title: 'Types of AI (Narrow AI vs General AI)', duration: 25 },
        { title: 'Fun AI Quiz', duration: 20, hasLab: 'quiz' }
      ]
    },
    {
      title: 'AI in Everyday Life',
      description: 'Explore how AI is integrated into mobile phones, entertainment recommendations, mapping, and shopping.',
      lessons: [
        { title: 'AI in Mobile Phones', duration: 15 },
        { title: 'AI in YouTube & Netflix Recommendations', duration: 20 },
        { title: 'AI in Google Maps', duration: 20 },
        { title: 'AI in Online Shopping', duration: 15 },
        { title: 'AI in Games', duration: 20 },
        { title: 'AI in Healthcare and Education', duration: 25 }
      ]
    },
    {
      title: 'Machine Learning Basics',
      description: 'Understand the fuel of AI. Learn how machines learn from data and distinguish training from testing.',
      lessons: [
        { title: 'What is Machine Learning?', duration: 20 },
        { title: 'How Machines Learn', duration: 25 },
        { title: 'Data: The Fuel of AI', duration: 20 },
        { title: 'Training vs Testing', duration: 15 },
        { title: 'Examples of Machine Learning', duration: 20 },
        { title: 'Lab: Basic Machine Learning Analogy', duration: 25, hasLab: 'ml' }
      ]
    },
    {
      title: 'Generative AI',
      description: 'Discover generative architectures, chatbots, text generation, image outputs, and limits of Generative AI.',
      lessons: [
        { title: 'What is Generative AI?', duration: 20 },
        { title: 'ChatGPT and AI Chatbots', duration: 20 },
        { title: 'AI Image Generation', duration: 25 },
        { title: 'AI Music and Video Generation', duration: 25 },
        { title: 'Benefits and Limitations', duration: 20 }
      ]
    },
    {
      title: 'Prompt Engineering',
      description: 'Master prompt design patterns, role-based prompts, instructions, context inputs, and prompt templates.',
      lessons: [
        { title: 'What is a Prompt?', duration: 15 },
        { title: 'Good vs Bad Prompts', duration: 20 },
        { title: 'Asking Better Questions', duration: 20 },
        { title: 'Role-Based Prompting', duration: 20 },
        { title: 'Prompt Templates', duration: 15 },
        { title: 'Lab: Refining Bad Prompts', duration: 25, hasLab: 'prompt' }
      ]
    },
    {
      title: 'AI Ethics & Safety',
      description: 'Explore responsible AI, data biases, deepfakes, privacy concerns, and security guidelines.',
      lessons: [
        { title: 'Responsible AI', duration: 20 },
        { title: 'Bias in AI', duration: 20 },
        { title: 'Fake Images & Deepfakes', duration: 25 },
        { title: 'Privacy', duration: 20 },
        { title: 'AI Hallucinations', duration: 15 },
        { title: 'Using AI Safely', duration: 20 }
      ]
    },
    {
      title: 'Hands-on AI Projects',
      description: 'Put your prompt writing skills to the test by creating story generators, quiz makers, and planners.',
      lessons: [
        { title: 'AI Story Generator', duration: 30, hasLab: 'story' },
        { title: 'AI Poster Creator', duration: 25 },
        { title: 'AI Quiz Maker', duration: 30, hasLab: 'quizmaker' },
        { title: 'AI Study Assistant', duration: 25 },
        { title: 'AI Travel Planner', duration: 30 }
      ]
    },
    {
      title: 'Future of AI',
      description: 'Map out future jobs, careers in machine learning, automation, and becoming an AI creator.',
      lessons: [
        { title: 'AI Careers', duration: 20 },
        { title: 'Robots and Automation', duration: 20 },
        { title: 'AI in Space', duration: 15 },
        { title: 'AI in Medicine', duration: 20 },
        { title: 'Future Jobs', duration: 20 },
        { title: 'Becoming an AI Creator', duration: 25 }
      ]
    }
  ];

  let modOrder = 1;
  for (const mData of modulesData) {
    const mod = await prisma.module.create({
      data: {
        courseId: course.id,
        title: mData.title,
        description: mData.description,
        sortOrder: modOrder++,
        isFree: modOrder === 2 // first module is free
      }
    });

    let lesOrder = 1;
    for (const lData of mData.lessons) {
      const les = await prisma.lesson.create({
        data: {
          moduleId: mod.id,
          title: lData.title,
          description: `Learn about ${lData.title.toLowerCase()} and complete associated exercises.`,
          sortOrder: lesOrder++,
          durationMins: lData.duration,
          isFree: lData.free || false
        }
      });

      // Fetch dynamic textbook content if it exists
      const textbookContent = lessonContents[lData.title] || `# ${lData.title}\n\nInformation about ${lData.title.toLowerCase()} is being populated. Please check back soon!`;

      // Seeding Steps
      const introStepId = makeStepId(les.id, 'intro');
      await prisma.lessonStep.create({
        data: {
          id: introStepId,
          lessonId: les.id,
          stepType: LessonStepType.intro,
          sortOrder: 1,
          title: `Welcome to ${lData.title}`,
          textContent: `# Lesson Overview: ${lData.title}

In this lesson, we will explore the core concepts of **${lData.title}**.

### Learning Goals:
* Understand the core concepts behind ${lData.title.toLowerCase()}.
* Discover real-world examples and use-cases.
* Test your understanding using active recall exercises.
`
        }
      });

      if (lData.hasLab) {
        const labStepId = makeStepId(les.id, 'lab');
        let labConfig: any = null;

        if (lData.hasLab === 'quiz') {
          labConfig = {
            title: 'Quiz: Narrow AI vs General AI',
            starterCode: `// Answer Siri/AGI types questions to pass!

function SiriAIType() {
  // Return either 'narrow' or 'general'
  return "";
}

function HumanLevelAIType() {
  // Return either 'narrow' or 'general'
  return "";
}

module.exports = { SiriAIType, HumanLevelAIType };
`,
            solutionCode: `function SiriAIType() {
  return "narrow";
}
function HumanLevelAIType() {
  return "general";
}
module.exports = { SiriAIType, HumanLevelAIType };
`,
            instructions: `### Narrow vs General AI Quiz
Write responses returning the correct types:
1. Siri is an example of **Narrow** AI (\`"narrow"\`).
2. AI matching human-level capabilities is **General** AI (\`"general"\`).`,
            labTestCode: {
              javascript: `
try {
  if (typeof SiriAIType === 'undefined' || typeof HumanLevelAIType === 'undefined') {
    throw new Error("Functions are not defined");
  }
  const siri = SiriAIType();
  const agi = HumanLevelAIType();
  const siriPassed = siri.toLowerCase() === "narrow";
  const agiPassed = agi.toLowerCase() === "general";
  console.log("[TEST_CASE] 0 | " + (siriPassed ? "PASS" : "FAIL") + " | Siri");
  console.log("[TEST_CASE] 1 | " + (agiPassed ? "PASS" : "FAIL") + " | AGI");
  if (siriPassed && agiPassed) {
    console.log("TEST_RESULTS: 2/2 passed");
  } else {
    console.log("TEST_FAILURE: Some test cases failed");
  }
} catch (e) {
  console.error("TEST_FAILURE: " + e.message);
  process.exit(1);
}
`
            }
          };
        } else if (lData.hasLab === 'ml') {
          labConfig = {
            title: 'Lab: Basic Fruits Classifier model',
            starterCode: `def classify_fruit(weight, color):
    # TODO: If weight is less than 20g and color is 'purple', return 'grape'.
    # If weight is greater than 100g and color is 'red', return 'apple'.
    # Else return 'unknown'.
    pass
`,
            solutionCode: `def classify_fruit(weight, color):
    if weight < 20 and color == 'purple':
        return 'grape'
    elif weight > 100 and color == 'red':
        return 'apple'
    return 'unknown'
`,
            instructions: `### Machine Learning Fruits Classification
Write a simple programmatic classifier:
* Return \`'grape'\` if \`weight < 20\` and \`color == 'purple'\`.
* Return \`'apple'\` if \`weight > 100\` and \`color == 'red'\`.
* Otherwise return \`'unknown'\`.`,
            labTestCode: {
              python: `
import sys
try:
    if 'classify_fruit' not in globals():
        raise NameError("Function classify_fruit is not defined")
    c1 = classify_fruit(15, 'purple') == 'grape'
    c2 = classify_fruit(120, 'red') == 'apple'
    c3 = classify_fruit(50, 'yellow') == 'unknown'
    passed = c1 and c2 and c3
    print(f"[TEST_CASE] 0 | {'PASS' if passed else 'FAIL'} | Classifier")
    if passed:
        print("TEST_RESULTS: 1/1 passed")
        sys.exit(0)
    else:
        sys.exit(1)
except Exception as e:
    print(f"TEST_FAILURE: {e}", file=sys.stderr)
    sys.exit(1)
`
            }
          };
        } else if (lData.hasLab === 'prompt') {
          labConfig = {
            title: 'Lab: Reconstructing Space Prompt',
            starterCode: `// Improve prompt "Tell me about space" into a targeted prompt.

function makeSpacePrompt() {
  // TODO: Return a refined prompt explaining the solar system to a 12-year-old
  // using simple language. Ensure the string contains '12-year-old' and 'solar system'.
  return "";
}

module.exports = { makeSpacePrompt };
`,
            solutionCode: `function makeSpacePrompt() {
  return "Explain the solar system to a 12-year-old using simple language and examples.";
}
module.exports = { makeSpacePrompt };
`,
            instructions: `### Reconstructing Prompts
Construct a prompt string containing key instructions:
* Must contain target audience \`"12-year-old"\`.
* Must contain subject \`"solar system"\`.`,
            labTestCode: {
              javascript: `
try {
  if (typeof makeSpacePrompt === 'undefined') {
    throw new Error("Function is not defined");
  }
  const act = makeSpacePrompt();
  const passed = act.includes("12-year-old") && act.includes("solar system");
  console.log("[TEST_CASE] 0 | " + (passed ? "PASS" : "FAIL") + " | Prompt Check");
  if (passed) {
    console.log("TEST_RESULTS: 1/1 passed");
  } else {
    console.log("TEST_FAILURE: Target keywords not found in prompt");
  }
} catch (e) {
  console.error("TEST_FAILURE: " + e.message);
  process.exit(1);
}
`
            }
          };
        } else if (lData.hasLab === 'story') {
          labConfig = {
            title: 'Lab: AI Story Generator Prompt',
            starterCode: `def make_story_prompt(hero, genre):
    # TODO: Return a string instructing an LLM to generate a story in 'genre'
    # starring 'hero'. Ensure the prompt contains both parameters.
    pass
`,
            solutionCode: `def make_story_prompt(hero, genre):
    return f"Write a {genre} story starring {hero}."
`,
            instructions: `### Dynamic Prompt Building
Complete the function to format LLM story instructions using python f-strings.`,
            labTestCode: {
              python: `
import sys
try:
    if 'make_story_prompt' not in globals():
        raise NameError("Function is not defined")
    act = make_story_prompt("Sherlock", "mystery")
    passed = "Sherlock" in act and "mystery" in act
    print(f"[TEST_CASE] 0 | {'PASS' if passed else 'FAIL'} | Prompt Formatter")
    if passed:
        print("TEST_RESULTS: 1/1 passed")
    else:
        sys.exit(1)
except Exception as e:
    sys.exit(1)
`
            }
          };
        } else if (lData.hasLab === 'quizmaker') {
          labConfig = {
            title: 'Lab: Quiz JSON Payload Formatter',
            starterCode: `// Write a function returning a valid JSON quiz structure.

function buildQuizJSON(topic, questionCount) {
  // TODO: Return a JSON string representing an object with properties:
  // 'topic' (string) and 'questions' (array of length questionCount).
  return "";
}

module.exports = { buildQuizJSON };
`,
            solutionCode: `function buildQuizJSON(topic, questionCount) {
  const obj = {
    topic: topic,
    questions: new Array(questionCount).fill("What is AI?")
  };
  return JSON.stringify(obj);
}
module.exports = { buildQuizJSON };
`,
            instructions: `### Formatting Structured Data
Convert dynamic parameters into a stringified JSON object containing:
* Property \`topic\`.
* Array \`questions\` with length matching \`questionCount\`.`,
            labTestCode: {
              javascript: `
try {
  if (typeof buildQuizJSON === 'undefined') {
    throw new Error("Function buildQuizJSON is not defined");
  }
  const raw = buildQuizJSON("Space", 3);
  const parsed = JSON.parse(raw);
  const passed = parsed.topic === "Space" && Array.isArray(parsed.questions) && parsed.questions.length === 3;
  console.log("[TEST_CASE] 0 | " + (passed ? "PASS" : "FAIL") + " | JSON Verification");
  if (passed) {
    console.log("TEST_RESULTS: 1/1 passed");
  } else {
    console.log("TEST_FAILURE: Validation failed");
  }
} catch (e) {
  console.error("TEST_FAILURE: " + e.message);
  process.exit(1);
}
`
            }
          };
        }

        if (labConfig) {
          await prisma.lessonStep.create({
            data: {
              id: labStepId,
              lessonId: les.id,
              stepType: LessonStepType.lab,
              sortOrder: 2,
              title: labConfig.title,
              labLanguage: lData.hasLab === 'ml' || lData.hasLab === 'story' ? 'python' : 'javascript',
              labStarterCode: labConfig.starterCode,
              labSolutionCode: labConfig.solutionCode,
              labInstructions: labConfig.instructions,
              labTestCode: labConfig.labTestCode,
              metadata: {
                examples: [
                  { input: "See instructions", output: "Matches verification rules" }
                ]
              }
            }
          });

          await prisma.assignment.create({
            data: {
              id: labStepId,
              courseId: course.id,
              moduleId: mod.id,
              title: labConfig.title,
              assignmentType: 'coding',
              status: AssignmentStatus.active,
              maxScore: 100,
              starterCode: labConfig.starterCode,
              language: lData.hasLab === 'ml' || lData.hasLab === 'story' ? 'python' : 'javascript'
            }
          });
        }
      } else {
        const textStepId = makeStepId(les.id, 'text');
        await prisma.lessonStep.create({
          data: {
            id: textStepId,
            lessonId: les.id,
            stepType: LessonStepType.text,
            sortOrder: 2,
            title: `Understanding ${lData.title}`,
            textContent: textbookContent
          }
        });
      }
    }
  }

  console.log('🎉 Beginner AI Course Seeding Completed!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
